version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: ./frontend
    command: yarn start
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./frontend/src:/app/src
  backend:
    build:
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
  postgres:
    image: postgres:9.6.2
    restart: always
    environment:
      POSTGRES_USER: 'sb_app'
      POSTGRES_PASSWORD: 'password@sb'
      POSTGRES_DB: 'sb_db'
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: