version: '3'
services:
  frontend:
    build:
      context: ./frontend
    command: 'yarn start'
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./frontend/src:/app/src
  backend:
    build:
      context: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
  postgres:
    image: 'postgres:9.6.2'
    restart: always
    environment:
      POSTGRES_USER: 'my_app'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'foo_bar'
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: